apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.privateaccesssecret.name }}
  namespace: {{ .Values.namespace }}
data:
  .dockerconfigjson: {{ .Values.privateaccesssecret.dockerconfigjson }}
type: kubernetes.io/dockerconfigjson