apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: {{ .Values.namespaceM }}
  name: {{ .Values.zblkubeeventroles.ServiceAccount.name }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ .Values.zblkubeeventroles.name }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: {{ .Values.zblkubeeventroles.roleRef.kind }}
  name: {{ .Values.zblkubeeventroles.roleRef.name}}
subjects:
  - kind: {{ .Values.zblkubeeventroles.subjects.kind }}
    namespace: {{ .Values.namespaceM }}
    name: {{ .Values.zblkubeeventroles.subjects.name }}