apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.zblappmongo.servicename }}
  namespace: {{ .Values.namespace }}
spec:
  ports:
    - port: {{ .Values.zblappmongo.port }}
      targetPort: {{ .Values.zblappmongo.targetport }}
      protocol: TCP
      name: http
  selector:
    app: {{ .Values.zblappmongo.labels }}