apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.namespace }}

---
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.namespaceRM }}

---
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.namespaceM }}

---
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.namespaceJ }}
 