apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata: 
  name: {{ .Values.Virtualservices.harbor.name }}
  namespace: {{ .Values.namespaceRM }}
spec: 
  gateways: 
    - {{ .Values.Gateway.nginx.name }}
  hosts: 
    - "{{ .Values.Virtualservices.harbor.subdomain }}.{{ .Values.domain }}"
  http: 
    - 
      match: 
        - 
          uri: 
            prefix: /api/
        - 
          uri: 
            prefix: /c/
        - 
          uri: 
            prefix: /chartrepo/
        - 
          uri: 
            prefix: /service/
        - 
          uri: 
            prefix: /v1/
        - 
          uri: 
            prefix: /v2/
      route: 
        - 
          destination: 
            host: {{ .Values.Virtualservices.harbor.hostone }}
            port: 
              number: {{ .Values.Virtualservices.harbor.port }}
    - 
      match: 
        - 
          uri: 
            prefix: /
      rewrite: 
        uri: /
      route: 
        - 
          destination: 
            host: {{ .Values.Virtualservices.harbor.hosttwo }}
            port: 
              number: {{ .Values.Virtualservices.harbor.port }}